[package]
name = "stewart-runtime-native"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
sharded-slab.workspace = true
tracing.workspace = true
stewart.workspace = true
stewart-local.workspace = true
