[package]
name = "stewart-native"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crossbeam.workspace = true
sharded-slab.workspace = true
tracing.workspace = true
stewart.workspace = true
stewart-runtime.workspace = true
