[package]
name = "ptero-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ptero"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
uuid.workspace = true
daicon.workspace = true
