[package]
name = "omfobj-viewer-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
omfobj-viewer = { path = "../omfobj-viewer" }
wasm-bindgen = "0.2.63"
console_error_panic_hook = "0.1.6"
